"use client";
import { useEffect,useMemo,useState } from "react";
import { cacheRecord,queueAction,queuedCount,readCachedRecord,startOfflineSync } from "@/lib/offline-queue";
type Student={id:string;admissionId:string;firstName:string;lastName:string;classId?:string|null};
type Assignment={id:string;class:{id:string;name:string;arm?:string|null;section:{name:string}};subject:{id:string;name:string}};
type Data={teacher:{teacherCode:string};assignments:Assignment[]};
type Score={ca1:string;ca2:string;ca3:string;ca4:string;exam:string;ca1SavedAt?:string|null;ca2SavedAt?:string|null;ca3SavedAt?:string|null;ca4SavedAt?:string|null;examSavedAt?:string|null};
type ScoreMap=Record<string,Score>;
type RecordItem={studentId:string;ca1:number|null;ca2:number|null;ca3:number|null;ca4:number|null;exam:number|null;ca1SavedAt?:string|null;ca2SavedAt?:string|null;ca3SavedAt?:string|null;ca4SavedAt?:string|null;examSavedAt?:string|null};
const W=24*60*60*1000; const CA=["ca1","ca2","ca3","ca4"] as const; const F=["ca1","ca2","ca3","ca4","exam"] as const;
const rem=(s?:string|null)=>s?Math.max(0,new Date(s).getTime()+W-Date.now()):null;
const fmt=(m:number|null)=>m===null?"":m<=0?"Correction window expired":Math.floor(m/3600000)+"h "+Math.floor(m%3600000/60000)+"m remaining for correction";
export default function ScoresPage(){
const [data,setData]=useState<Data|null>(null),[students,setStudents]=useState<Student[]>([]),[selected,setSelected]=useState(""),[term,setTerm]=useState("First Term"),[scores,setScores]=useState<ScoreMap>({}),[schoolId,setSchoolId]=useState(""),[online,setOnline]=useState(true),[pending,setPending]=useState(0),[message,setMessage]=useState("Loading..."),[scope,setScope]=useState("");
const assignment=useMemo(()=>data?.assignments.find(x=>x.id===selected)??data?.assignments[0]??null,[data,selected]);
async function load(){let me:any=null;try{const r=await fetch("/api/auth/me");const n=await r.json().catch(()=>({}));if(r.ok){me=n;cacheRecord("skulgo-current-me",n)}}catch{me=readCachedRecord<any>("skulgo-current-me")}if(!me)me=readCachedRecord<any>("skulgo-current-me");const sk=me?.user?.id&&me?.user?.membership?.id?me.user.id+":"+me.user.membership.id:"";setScope(sk);if(!sk){setMessage("This school workspace is not available on this device yet.");return}let d:any=null;try{const r=await fetch("/api/schools/current/my-assignments");const n=await r.json().catch(()=>({}));if(r.ok){d=n;cacheRecord("skulgo:"+sk+":my-assignments",n)}}catch{d=readCachedRecord<Data>("skulgo:"+sk+":my-assignments")}if(!d)d=readCachedRecord<Data>("skulgo:"+sk+":my-assignments");if(!d){setMessage("Teacher assignments are not available on this device yet.");return}setData(d);setSchoolId(me?.user?.membership?.schoolId??"");if(!selected&&d.assignments?.length)setSelected(d.assignments[0].id);setMessage("")}
async function loadStudents(){if(!schoolId||!assignment)return;const k="skulgo-scores-students-"+schoolId+"-"+assignment.class.id;try{const r=await fetch("/api/schools/"+schoolId+"/students");if(r.ok){const b=await r.json();const f=b.filter((x:Student)=>!x.classId||x.classId===assignment.class.id);setStudents(f);cacheRecord(k,f);return}}catch{}setStudents(readCachedRecord<Student[]>(k)??[])}
async function loadScores(){if(!schoolId||!assignment)return;const k="skulgo:"+scope+":assessments-"+assignment.id+"-"+term;try{const r=await fetch("/api/schools/"+schoolId+"/assessments?classId="+encodeURIComponent(assignment.class.id)+"&subjectId="+encodeURIComponent(assignment.subject.id)+"&term="+encodeURIComponent(term));if(r.ok){const b=await r.json() as RecordItem[];const n:ScoreMap={};for(const x of b)n[x.studentId]={ca1:x.ca1==null?"":String(x.ca1),ca2:x.ca2==null?"":String(x.ca2),ca3:x.ca3==null?"":String(x.ca3),ca4:x.ca4==null?"":String(x.ca4),exam:x.exam==null?"":String(x.exam),ca1SavedAt:x.ca1SavedAt??null,ca2SavedAt:x.ca2SavedAt??null,ca3SavedAt:x.ca3SavedAt??null,ca4SavedAt:x.ca4SavedAt??null,examSavedAt:x.examSavedAt??null};setScores(n);cacheRecord(k,n);return}}catch{}setScores(readCachedRecord<ScoreMap>(k)??{})}
function setScore(id:string,f:typeof F[number],v:string){const c=scores[id]??{ca1:"",ca2:"",ca3:"",ca4:"",exam:""};setScores({...scores,[id]:{...c,[f]:v}})}
async function save(st:Student){if(!schoolId||!assignment)return;const s=scores[st.id]??{ca1:"",ca2:"",ca3:"",ca4:"",exam:""};const body:any={studentId:st.id,classId:assignment.class.id,subjectId:assignment.subject.id,term};let count=0;for(const f of F){const v=s[f].trim();if(!v)continue;const at=f==="exam"?s.examSavedAt:s[(f+"SavedAt") as keyof Score] as string|null|undefined;if(at&&rem(at)===0){setMessage(f.toUpperCase()+" correction window expired.");return}const n=Number(v),max=f==="exam"?60:10;if(!Number.isFinite(n)||n<0||n>max){setMessage(f.toUpperCase()+" must be 0-"+max+".");return}body[f]=n;count++}if(!count){setMessage("Enter at least one CA component or exam score before saving.");return}if(!navigator.onLine){queueAction({scopeKey:scope,url:"/api/schools/"+schoolId+"/assessments",method:"POST",body});setPending(queuedCount(scope));setMessage("Saved on this device. It will sync automatically when internet returns.");return}try{const r=await fetch("/api/schools/"+schoolId+"/assessments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const z=await r.json().catch(()=>({}));if(!r.ok){setMessage(z.error||"Score could not be saved.");return}setScores(p=>({...p,[st.id]:{...p[st.id],ca1:z.ca1==null?"":String(z.ca1??p[st.id]?.ca1??""),ca2:z.ca2==null?"":String(z.ca2??p[st.id]?.ca2??""),ca3:z.ca3==null?"":String(z.ca3??p[st.id]?.ca3??""),ca4:z.ca4==null?"":String(z.ca4??p[st.id]?.ca4??""),exam:z.exam==null?"":String(z.exam??p[st.id]?.exam??""),ca1SavedAt:z.ca1SavedAt??p[st.id]?.ca1SavedAt??null,ca2SavedAt:z.ca2SavedAt??p[st.id]?.ca2SavedAt??null,ca3SavedAt:z.ca3SavedAt??p[st.id]?.ca3SavedAt??null,ca4SavedAt:z.ca4SavedAt??p[st.id]?.ca4SavedAt??null,examSavedAt:z.examSavedAt??p[st.id]?.examSavedAt??null}}));setMessage("Saved. Each entered component has its own 24-hour correction window.")}catch{queueAction({scopeKey:scope,url:"/api/schools/"+schoolId+"/assessments",method:"POST",body});setPending(queuedCount(scope));setMessage("Connection dropped. Saved on this device and queued for sync.")}}
useEffect(()=>{setOnline(navigator.onLine);setPending(queuedCount(scope));void load();const on=()=>{setOnline(true);startOfflineSync(scope,r=>setPending(r.remaining))},off=()=>setOnline(false);window.addEventListener("online",on);window.addEventListener("offline",off);return()=>{window.removeEventListener("online",on);window.removeEventListener("offline",off)}},[scope]);
useEffect(()=>{void loadStudents();void loadScores()},[schoolId,assignment?.id,term,scope]);
if(!data)return <main className="workspace-main"><p className="muted">{message}</p></main>;
if(!assignment)return <main className="workspace-main"><div className="card"><strong>No teaching assignment yet.</strong><p className="muted">Scores will appear here after Admin assigns a class and subject.</p></div></main>;
return <main className="workspace-main"><div className="workspace-header"><p className="muted">Teacher workspace · {online?"Online":"Offline"}</p><h1>Scores</h1><p className="muted">{assignment.subject.name} · {assignment.class.section.name} · {assignment.class.name}{assignment.class.arm?" · "+assignment.class.arm:""}</p><p className="muted">{pending?pending+" item(s) waiting to sync":"Saved records sync automatically."}</p></div><div className="card" style={{marginBottom:18}}><div className="grid grid-2"><label className="grid"><span>Teaching assignment</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{data.assignments.map(x=><option key={x.id} value={x.id}>{x.subject.name} · {x.class.section.name} · {x.class.name}{x.class.arm?" · "+x.class.arm:""}</option>)}</select></label><label className="grid"><span>Term</span><select value={term} onChange={e=>setTerm(e.target.value)}><option>First Term</option><option>Second Term</option><option>Third Term</option></select></label></div></div>{!students.length?<div className="card"><strong>No students available.</strong></div>:<div className="grid">{students.map(st=>{const s=scores[st.id]??{ca1:"",ca2:"",ca3:"",ca4:"",exam:""};return <div className="card" key={st.id}><strong>{st.firstName} {st.lastName}</strong><p className="muted">{st.admissionId}</p><strong>CA / 40</strong><div className="grid grid-2">{CA.map(f=>{const at=s[(f+"SavedAt") as keyof Score] as string|null|undefined;const left=rem(at);const lock=Boolean(at)&&left===0;return <label className="grid" key={f}><span>{f.toUpperCase()} / 10</span><input inputMode="decimal" value={s[f]} disabled={lock} onChange={e=>setScore(st.id,f,e.target.value)}/>{at&&<small className="muted">{lock?"Correction window expired.":fmt(left)}</small>}</label>})}</div><label className="grid"><span>Exam / 60</span><input inputMode="decimal" value={s.exam} disabled={Boolean(s.examSavedAt)&&rem(s.examSavedAt)===0} onChange={e=>setScore(st.id,"exam",e.target.value)}/>{s.examSavedAt&&<small className="muted">{fmt(rem(s.examSavedAt))}</small>}</label><button className="button" onClick={()=>void save(st)}>Save entered score(s)</button></div>})}</div>}{message&&<p>{message}</p>}</main>}
