export const STARTER_SUBJECTS: Record<string, string[]> = {
  Nursery: [
    "English",
    "Mathematics",
    "Basic Science",
    "Social Habits",
    "Health Habits",
    "Creative Arts",
    "Rhymes",
  ],
  Primary: [
    "English Studies",
    "Mathematics",
    "Basic Science",
    "Basic Technology",
    "Social Studies",
    "Civic Education",
    "Computer Studies",
    "Agricultural Science",
    "Home Economics",
    "Physical and Health Education",
    "Cultural and Creative Arts",
    "Christian Religious Studies / Islamic Religious Studies",
  ],
  "Junior Secondary": [
    "English Studies",
    "Mathematics",
    "Basic Science",
    "Basic Technology",
    "Computer Studies",
    "Business Studies",
    "Social Studies",
    "Civic Education",
    "Agricultural Science",
    "Home Economics",
    "Cultural and Creative Arts",
    "Christian Religious Studies / Islamic Religious Studies",
    "French",
  ],
  "Senior Secondary": [
    "English Language",
    "Mathematics",
    "Civic Education",
    "Biology",
    "Chemistry",
    "Physics",
    "Economics",
    "Government",
    "Geography",
    "Literature in English",
    "Financial Accounting",
    "Commerce",
    "Computer Studies",
    "Agricultural Science",
    "Christian Religious Studies / Islamic Religious Studies",
  ],
};

export function starterSubjects(sectionName: string) {
  return STARTER_SUBJECTS[sectionName] ?? [];
}
